site_name: UITK Implementation
site_url: https://sbuplakankus.github.io/uitk-vr-implementation/
repo_url: https://github.com/SBUplakankus/uitk-vr-implementation  
repo_name: UITK VR

theme:
  name: material
  favicon: assets/images/tablet.svg
  logo: assets/images/tablet.svg
  font:
    text: Roboto
    code: Roboto Mono
  icons:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-outline
        name: Switch to light mode
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  features:
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - search.suggest        
    - search.highlight     
    - content.code.copy 

nav:
  - Home: index.md
  - Reference:
      - Unity: references/uitk_refs.md
  - Research:
      - Design Patterns: research/design_patterns.md
      - Shader Graph: research/shader_graph.md
      - VR Integration: research/vr_integration.md
      - Web To USS: research/web_to_uss.md
  - AI Overview:
      - Performance: ai/performance.md
      - Bagel Game Analysis: ai/bg_analysis.md
      - Industry UITK Practices: ai/industry_uitk.md
      - Layer Architecture: ai/layer_architecture.md
      - M-V-VM: ai/mvvm.md
  - AI Examples:
      - C# Implementation: ai/cs_implementation.md
      - USS Implementation: ai/uss_implementation.md
      - USS Analysis: ai/uss_analysis.md
      - USS Overlay (Bonus): ai/uss_overlay_bonus.md

plugins:
  - search    
